// packages/marimo-studio/src/marimo_studio/view_providers/_bundled/deno_svelte/starters/default/files/src/App.svelte
<script lang="ts">
  const notebookLabel = __NOTEBOOK_LABEL_JSON__;
  const viewHeading = __VIEW_HEADING_JSON__;
  let resultsVisible = $state(true);
</script>

<div class="page">
  <header class="page-header">
    <div>
      <p>{notebookLabel}</p>
      <h1>{viewHeading}</h1>
    </div>
    <button type="button" onclick={() => (resultsVisible = !resultsVisible)}>
      {resultsVisible ? "Hide results" : "Show results"}
    </button>
  </header>

  {#if resultsVisible}
    <section class="results" aria-label="Notebook results">
      __NOTEBOOK_CELL_HOSTS_SVELTE__
    </section>
  {/if}
</div>

// packages/marimo-studio/src/marimo_studio/view_providers/_builtin/deno_react/starters/default/files/src/App.tsx
/// <reference path="./marimo-studio.d.ts" />

const NOTEBOOK_LABEL = __NOTEBOOK_LABEL_JSON__;
const VIEW_HEADING = __VIEW_HEADING_JSON__;

export const App = () => (
  <div className="page">
    <header className="page-header">
      <p>{NOTEBOOK_LABEL}</p>
      <h1>{VIEW_HEADING}</h1>
    </header>
    <section className="results" aria-label="Notebook results">
      __NOTEBOOK_CELL_HOSTS_TSX__
    </section>
  </div>
);
